 const cities = [
  "Bradley,CA",
  "San Ardo,CA",
  "Salinas,CA",
  "Big Sur,CA",
  "Carmel By The Sea,CA",
  "Carmel,CA",
  "Carmel Valley,CA",
  "Chualar,CA",
  "Gonzales,CA",
  "Greenfield,CA",
  "Jolon,CA",
  "King City,CA",
  "Lockwood,CA",
  "Marina,CA",
  "Monterey,CA",
  "Pacific Grove,CA",
  "Pebble Beach,CA",
  "San Lucas,CA",
  "Seaside,CA",
  "Soledad,CA",
  "Spreckels,CA",
  "Belmont,CA",
  "Brisbane,CA",
  "Burlingame,CA",
  "Daly City,CA",
  "El Granada,CA",
  "Half Moon Bay,CA",
  "La Honda,CA",
  "Loma Mar,CA",
  "Los Altos,CA",
  "Menlo Park,CA",
  "Atherton,CA",
  "Portola Valley,CA",
  "Millbrae,CA",
  "Mountain View,CA",
  "Montara,CA",
  "Moss Beach,CA",
  "Pacifica,CA",
  "Pescadero,CA",
  "Redwood City,CA",
  "San Bruno,CA",
  "San Carlos,CA",
  "San Gregorio,CA",
  "South San Francisco,CA",
  "Sunnyvale,CA",
  "San Francisco,CA",
  "Palo Alto,CA",
  "Stanford,CA",
  "San Mateo,CA",
  "Alameda,CA",
  "American Canyon,CA",
  "Discovery Bay,CA",
  "Danville,CA",
  "Alamo,CA",
  "Angwin,CA",
  "Antioch,CA",
  "Benicia,CA",
  "Bethel Island,CA",
  "Birds Landing,CA",
  "Brentwood,CA",
  "Byron,CA",
  "Calistoga,CA",
  "Canyon,CA",
  "Clayton,CA",
  "Concord,CA",
  "Pleasant Hill,CA",
  "Crockett,CA",
  "Diablo,CA",
  "El Cerrito,CA",
  "Fairfield,CA",
  "Travis Afb,CA",
  "Fremont,CA",
  "Hayward,CA",
  "Castro Valley,CA",
  "Hercules,CA",
  "Knightsen,CA",
  "Lafayette,CA",
  "Livermore,CA",
  "Martinez,CA",
  "Moraga,CA",
  "Napa,CA",
  "Newark,CA",
  "Oakley,CA",
  "Oakville,CA",
  "Orinda,CA",
  "Pinole,CA",
  "Pittsburg,CA",
  "Pleasanton,CA",
  "Pope Valley,CA",
  "Dublin,CA",
  "Port Costa,CA",
  "Rio Vista,CA",
  "Rodeo,CA",
  "Rutherford,CA",
  "Saint Helena,CA",
  "Deer Park,CA",
  "San Leandro,CA",
  "San Lorenzo,CA",
  "San Ramon,CA",
  "Suisun City,CA",
  "Sunol,CA",
  "Union City,CA",
  "Vallejo,CA",
  "Walnut Creek,CA",
  "Yountville,CA",
  "Oakland,CA",
  "Emeryville,CA",
  "Piedmont,CA",
  "Berkeley,CA",
  "Albany,CA",
  "Richmond,CA",
  "El Sobrante,CA",
  "San Pablo,CA",
  "San Rafael,CA",
  "Greenbrae,CA",
  "Kentfield,CA",
  "Belvedere Tiburon,CA",
  "Bodega,CA",
  "Bodega Bay,CA",
  "Bolinas,CA",
  "Corte Madera,CA",
  "Rohnert Park,CA",
  "Dillon Beach,CA",
  "Fairfax,CA",
  "Cotati,CA",
  "Forest Knolls,CA",
  "Inverness,CA",
  "Lagunitas,CA",
  "Larkspur,CA",
  "Marshall,CA",
  "Mill Valley,CA",
  "Novato,CA",
  "Nicasio,CA",
  "Olema,CA",
  "Penngrove,CA",
  "Petaluma,CA",
  "Point Reyes Station,CA",
  "Ross,CA",
  "San Anselmo,CA",
  "San Geronimo,CA",
  "San Quentin,CA",
  "Sausalito,CA",
  "Stinson Beach,CA",
  "Tomales,CA",
  "Valley Ford,CA",
  "Woodacre,CA",
  "Aptos,CA",
  "Alviso,CA",
  "Aromas,CA",
  "Ben Lomond,CA",
  "Boulder Creek,CA",
  "Brookdale,CA",
  "Campbell,CA",
  "Capitola,CA",
  "Castroville,CA",
  "Coyote,CA",
  "Cupertino,CA",
  "Davenport,CA",
  "Felton,CA",
  "Freedom,CA",
  "Gilroy,CA",
  "Hollister,CA",
  "Holy City,CA",
  "Los Gatos,CA",
  "Milpitas,CA",
  "Morgan Hill,CA",
  "Moss Landing,CA",
  "Mount Hermon,CA",
  "New Almaden,CA",
  "Paicines,CA",
  "Redwood Estates,CA",
  "San Juan Bautista,CA",
  "San Martin,CA",
  "Santa Clara,CA",
  "Santa Cruz,CA",
  "Scotts Valley,CA",
  "Saratoga,CA",
  "Soquel,CA",
  "Tres Pinos,CA",
  "Watsonville,CA",
  "San Jose,CA",
  "Mount Hamilton,CA",
  "Stockton,CA",
  "Acampo,CA",
  "Clements,CA",
  "Farmington,CA",
  "French Camp,CA",
  "Holt,CA",
  "Linden,CA",
  "Lockeford,CA",
  "Lodi,CA",
  "Victor,CA",
  "Woodbridge,CA",
  "Tracy,CA",
  "Escalon,CA",
  "Lathrop,CA",
  "Manteca,CA",
  "Ripon,CA",
  "Santa Rosa,CA",
  "Annapolis,CA",
  "Boyes Hot Springs,CA",
  "Camp Meeker,CA",
  "Cazadero,CA",
  "Cloverdale,CA",
  "Duncans Mills,CA",
  "Eldridge,CA",
  "El Verano,CA",
  "Forestville,CA",
  "Fulton,CA",
  "Geyserville,CA",
  "Glen Ellen,CA",
  "Graton,CA",
  "Guerneville,CA",
  "Healdsburg,CA",
  "Jenner,CA",
  "Kenwood,CA",
  "Monte Rio,CA",
  "Occidental,CA",
  "Rio Nido,CA",
  "Sebastopol,CA",
  "Sonoma,CA",
  "Stewarts Point,CA",
  "Villa Grande,CA",
  "Vineburg,CA",
  "Windsor,CA",
  "The Sea Ranch,CA",
  "Dixon,CA",
  "Elmira,CA",
  "Thornton,CA",
  "Vacaville,CA",
];

module.exports= cities